on:
  schedule:
    - cron: 0 0 */7 * *
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  star_list_job:
    runs-on: ubuntu-latest
    name: A job to get starred repos and update README
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run index.js
        uses: ./
        id: star-list
        with:
          pat: ${{ secrets.pat }}
          user: Cygra
          email: sjtuwbh@gmail.com
          repo: star-list
          file: README.md
